### ISSUE TITLE
Upgrade to React 17?

### ISSUE THREAD

**Issue by philipjohn** [karen-sarkisyan/react-wordpress-comments#1]
The `peerDependency` in this package means that it can't be installed in a project that uses React v17 and above. I'm not sure if there are compatibility issues with 17 or not. Perhaps it's just a versioning change that's needed?

Here's what I saw when trying to install in my project with a react dependency of `"react": "^17.0.2"`:

> npm ERR! code ERESOLVE
> npm ERR! ERESOLVE unable to resolve dependency tree
> npm ERR! 
> npm ERR! While resolving: lichfield-live@0.1.0
> npm ERR! Found: react@17.0.2
> npm ERR! node_modules/react
> npm ERR!   react@"^17.0.2" from the root project
> npm ERR! 
> npm ERR! Could not resolve dependency:
> npm ERR! peer react@"^16.8" from react-wordpress-comments@0.0.2
> npm ERR! node_modules/react-wordpress-comments
> npm ERR!   react-wordpress-comments@"*" from the root project
> npm ERR! 
> npm ERR! Fix the upstream dependency conflict, or retry
> npm ERR! this command with --force, or --legacy-peer-deps
> npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

**Comment by karen-sarkisyan** [comment]
Hi!
Thank you for trying `react-wordpress-comments` and providing feedback. Yeah, I don't expect any compatibility issues, I will update peer deps versions and release a new version of the package shortly.

In the meantime, you may try a workaround if you want: simply copy and paste source code to your project as I suggested [here](https://gridsound.com/daw/).

Feel free to contact me and/or submit any other feedback or bug reports.

**Comment by karen-sarkisyan** [comment]
You can now grab a package with a fix, version `0.0.3` from NPM. Reopen issue if it doesn't fix your problem.
