### ISSUE TITLE
The UI is not changeable

### ISSUE THREAD

**Issue by Habib2959** [karen-sarkisyan/react-wordpress-comments#5]
This would me helpful, if we can change the UI's of the replies and it will look better if you can change the look of cancel button.

**Comment by karen-sarkisyan** [comment]
Hi @Habib2959 ,
thanks for using this project. Here are the ways you can alter the cancel button:

1. Cancel link does not have a dedicated class, but you could use a regular CSS selector, for example like this.

```css
.reply-title a {
    color: red;
}
```

2. To change text on the link/button (the one with 'Cancel X' text on demo), pass an object to `translationOverrides` prop of the component. The object's `cancelLinkLabel` property can be set to the text you need.

3. If you want to actually make it look like a button, you could also use CSS. Take a look at this [example on stackoverflow](https://stackoverflow.com/questions/710089/how-do-i-make-an-html-link-look-like-a-button).

Hope that helps. Let me know if you need any further help.
I'll close this issue in a few days.
